### ISSUE TITLE
Non-russian IP blocked from russian sites & NoRussian site blocked for russian IP

### ISSUE THREAD

**Issue by voidpunk** [ajax-lives/NoRussian#11]
As from title, all those sites are inaccessible (error 504) from non-russian IP, when using a russian IP (VPNgate), those websites are reachable, but the stop-russian-desinformation.near.page isn't reachable (ERR_CONNECTION_RESET).

The code works locally, but the formatting is terrible. I'll try to fix it on monday.

**Comment by ajax-lives** [comment]
That can mean many things.

Your IP could be getting blocked from some sites for obvious reason.

Some sites are firewalled now to only within Russia.

stop-russian-desinformation.near.page is not us, so not relevant.

Our webpage blocks any Russian or Chinese IP.

Anyhow, this is not a valid issue, as you've given no examples or detail regarding a problem, with our code or site in specific.

So I'll be closing the issue, if you have further info, or updates, please re-open it.  Looking forward to hearing back.

Thanks!
