### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Ycirn** [ajax-lives/NoRussian#24]

**Comment by jora535** [comment]
Конченые пидарасы здохните ублюдки

**Comment by Ycirn** [comment]
> Конченые пидарасы здохните ублюдки

Get out of here, child murder supporter.

**Comment by ajax-lives** [comment]
Looks like the domain was blackholed by the registrar, grabbing a new one.

**Comment by thibaultmol** [comment]
Filed a report with github for that comment
https://support.github.com/contact/report-abuse?category=report-content&report=other&report_type=unspecified#contact_comments

**Comment by Ycirn** [comment]
Yeah report the Russian telling us to die

**Comment by ajax-lives** [comment]
Site has been moved to http://norussian.xyz
