### ISSUE TITLE
It's getting slow.

### ISSUE THREAD

**Issue by Ycirn** [ajax-lives/NoRussian#35]
Can anyone and try to speed it up?

**Comment by dimention** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/6980263/156062956-a3324088-4655-4632-aa42-01f47051d579.png">
sites that are down (or geoblocked) are still getting requested, this is a waste of resources, you can request them, but slow the requests down to them

**Comment by Ycirn** [comment]
Downed ones need to keep getting hit, is there a way to know which are geoblocked without manually testing them?

**Comment by dimention** [comment]
No there isn't a way. Down ones have to be pinged lets say every 10s to see if they are still down and if they are not, add to the full target list. I would suggest if 90% of responses are 200, they should be added to the full atack mode.

**Comment by Ycirn** [comment]
I notice a lot of traffic is http1/1, forcing it to http2 in the browser would minimalistically improve it. Is there a way to force http2/0 from the site? doubt it

**Comment by ajax-lives** [comment]
Speed will be determined by the concurrent requests and timeout.  As people keep pull requesting sites, there will be less request to individual sites, therefore those have to be changed.

However, it requires hefty amounts of testing to ensure effectiveness.

**Comment by Ycirn** [comment]
> Speed will be determined by the concurrent requests and timeout. As people keep pull requesting sites, there will be less request to individual sites, therefore those have to be changed.
> 
> However, it requires hefty amounts of testing to ensure effectiveness.

Its at 2 requests per seconds now @ajax-lives

**Comment by MadKamel** [comment]
What if somebody just goes through the list and removes all the less-important sites? I'm certain that lenta.ru and other news sites are a bit less important than bank websites and government record sites like gosuslugi.ru.

**Comment by Ycirn** [comment]
Removed useless and duplicate links #51
