### ISSUE TITLE
Suggestion: add https://rusvesna.su/

### ISSUE THREAD

**Issue by bdifferent** [ajax-lives/NoRussian#36]
Not sure if it's an issue, just wanted to create a thread for other really malicious russian sites to be added. Figured not worth creating a pull request for one but maybe we can get a bunch in.

My suggestion: https://rusvesna.su/ - really aggressive propoganda rupor. Been showing videos of Ukrainians allegedly deserting/surrendering, etc.

EDIT: I am aware the number of sites is already big but a lot of them are down already and this one is working perfectly fine and I don't see it being targeted by anyone.

**Comment by Ycirn** [comment]
Ill add it in a hour or so, also going to add more Belarus gov sites.

**Comment by Ycirn** [comment]
#40

**Comment by Caranthir** [comment]
You can also add https://rttv.com/ which is a domain of rt and appearantly they do the tv streaming over this domain

**Comment by Ycirn** [comment]
added with #51

**Comment by MadKamel** [comment]
You should close this, @ajax-lives

**Comment by MadKamel** [comment]
#35 should get closed too
