### ISSUE TITLE
No USA, NO WAR!!!

### ISSUE THREAD

**Issue by ASheaJin** [ajax-lives/NoRussian#41]

**Comment by 3inchtime** [comment]
No USA No War

**Comment by Itroublve** [comment]
No humans, no war. Just go kys everyone.

**Comment by MadKamel** [comment]
What's this all about? Isn't America staying out of Ukraine?

**Comment by Itroublve** [comment]
> What's this all about? Isn't America staying out of Ukraine?

Ignore smh
