### ISSUE TITLE
New sites from IT army, but unsure if we should add them.

### ISSUE THREAD

**Issue by Ycirn** [ajax-lives/NoRussian#46]
These are DDoS protection services that the IT army of Ukraine wants people to hit. Meaning a lot of sites besides the ones we are hitting are behind these services. IDK if we should add those though..

https://ddos-guard.net/ru
https://stormwall.pro/
https://qrator.net/ru/
https://solidwall.ru/

**Comment by MadKamel** [comment]
I think they meant that somebody should break in and take them down to make it easier to DDoS other sites, not DDoS a DDoS protection service. This doesn't seem like it'd be especially useful to add as a DDoS target.
