### ISSUE TITLE
distributed Distributed-Denial-Of-Service

### ISSUE THREAD

**Issue by Curid** [ajax-lives/NoRussian#5]
You realize that your isp will probably just cache the responses.

Even if they don't, what make you think that Russia doesn't have separate routes for domestic vs foreign requests.

Running this from outside of Russia won't affect domestic users at all.

If the idea is for Russian citizens to run it then that's a good way for them to get arrested in the middle of the night.

**Comment by timof121** [comment]
its not like a tcp flooder. its http* requests that still load their (server(s))

**Comment by Curid** [comment]
@ajax-lives Why do you close issues without a explanation?

**Comment by ajax-lives** [comment]
This isn't an issue.
These are complaints that you have with our software and goals.
