### ISSUE TITLE
Phishing attempts

### ISSUE THREAD

**Issue by seirdotexe** [ajax-lives/NoRussian#50]
One of these websites links to mine[.]exchange, which is a phishing [website](https://www.virustotal.com/gui/url/54b677a82144c36dc3e0982ce500058bd9548edaf87ddc98644978345145be54/detection).

Who knows what they gather about you.

**Comment by Ycirn** [comment]
IT army of Ukraine: "P2P crypto exchange connected to Sber, VTB and others Russian banks. Make them cry!".

I'd say keep hitting it.
