### ISSUE TITLE
Suggestion: add rutube.ru

### ISSUE THREAD

**Issue by diegoami** [ajax-lives/NoRussian#57]
I am not sure about that, it seems to me that it is also dominated by russian propaganda.

**Comment by Ycirn** [comment]
No, its a youtube clone but poorly managed, theres lots of pro Ukranian content on there trying to show Russians whats going on in Ukraine

**Comment by MadKamel** [comment]
Oh, good we didn't add it.

**Comment by MadKamel** [comment]
What's with the name change though?
