### ISSUE TITLE
US and NATO are the main obstacle of world peace.

### ISSUE THREAD

**Issue by JiangYanting** [ajax-lives/NoRussian#68]

**Comment by MadKamel** [comment]
This is not related, @ajax-lives might want to close this.

If you feel like it, you can express your political opinion elsewhere, like Twitter. Not on a github issue.

**Comment by JiangYanting** [comment]
> This is not related, @ajax-lives might want to close this.
> 
> If you feel like it, you can express your political opinion elsewhere, like Twitter. Not on a github issue.

However, It is this repository that attack Russia and  Belarussian websites first. Does this repository keep political neutrality？Where is freedom?

**Comment by JiangYanting** [comment]
> This is not related, @ajax-lives might want to close this.
> 
> If you feel like it, you can express your political opinion elsewhere, like Twitter. Not on a github issue.

However, It is this repository that attack Russia and  Belarussian websites first. Does this repository keep political neutrality？

**Comment by JiangYanting** [comment]
> This is not related, @ajax-lives might want to close this.
> 
> If you feel like it, you can express your political opinion elsewhere, like Twitter. Not on a github issue.

However, It is this repository that attacked Russia and  Belarussian websites first. Does this repository keep political neutrality？

**Comment by Ycirn** [comment]
> > This is not related, @ajax-lives might want to close this.
> > If you feel like it, you can express your political opinion elsewhere, like Twitter. Not on a github issue.
> 
> However, It is this repository that attacked Russia and Belarussian websites first. Does this repository keep political neutrality？

And its Russia and Belarussia that attacked Ukraine out of no where for the sake of restarting some deprecated form of the Soviet Union again, it is Russia and Belarussia that are committing horrible war crimes right now, it is Russia that is lying to all their citizens about whats happening, it is Russia that is sending people to jail for mentioning the war. Russia is 10 times worse than NATO

**Comment by JiangYanting** [comment]
> However, It is this repository that attacked Russia and Belarussian websites first. Does this repository keep political neutrality？
Hi, I'm from China. With all due respect, let me tell you something.
  Firstly,I know Twitter, Facebook and other social media are banning news, essays and accounts which support Russia. And what you see from media is likely to be biased. Does "western freedom" mean only allowing one to criticize the other, while the other cannot speak?
  Secondly, I know that Ukraine president is tolerant towards new Nazi organization “Azov Battalion”, which admired Adolf Hitler and killed lots of innocent people in the eastern Ukraine.
  Thirdly, US and NATO invaded Yugoslavia in 1999, invaded Afghanistan in 2001, invaded Iraq in 2003, invaded Libya in 2011, causing war, bleeding, poverty and death. Does these mean justice and freedom? 
[https://pics1.baidu.com/feed/d53f8794a4c27d1e8cbe5d0a33df5467dcc43873.png?token=1643c839ba48604ee165dd189b6fce2d](url)

**Comment by Ycirn** [comment]
> Firstly,I know Twitter, Facebook and other social media are banning news, essays and accounts which support Russia. And what you see from media is likely to be biased. Does "western freedom" mean only allowing one to criticize the other, while the other cannot speak?

Facebook and Twitter are banning accounts that say there is nothing bad going on in Ukraine. Which is the complete opposite of what is going on.

> Secondly, I know that Ukraine president is tolerant towards new Nazi organization “Azov Battalion”, which admired Adolf Hitler and killed lots of innocent people in the eastern Ukraine.

You do realize that Zelensky is Jewish right?? Every country has far right-wing organizations like this, the moment you stop them they just start over again. Would be surprised if you could give me an example of a country that has completely stopped far right-wing organizations like this.

> Thirdly, US and NATO invaded Yugoslavia in 1999, invaded Afghanistan in 2001, invaded Iraq in 2003, invaded Libya in 2011, causing war, bleeding, poverty and death. Does these mean justice and freedom?

Do you even know what was going on in Yugoslavia at the time? I recommend reading about it. The middle eastern countries were invaded. Also as for Afghanistan. Russia did what it's doing in Ukraine right now with the start of Operation Storm-333. This caused lots of unrest between civilians which eventually lead to war and organizations which were trying to create peace in the country. Those organizations were later funded by the USA/UN trying to make them succeed. This failed horrible due to corruption in said organizations, which lead to the USA/UN invading Afghanistan in 2001. Educate yourself.

Now stop talking about this.

**Comment by JiangYanting** [comment]
> > Firstly,I know Twitter, Facebook and other social media are banning news, essays and accounts which support Russia. And what you see from media is likely to be biased. Does "western freedom" mean only allowing one to criticize the other, while the other cannot speak?
> 
> Facebook and Twitter are banning accounts that say there is nothing bad going on in Ukraine. Which is the complete opposite of what is going on. Also you're Chinese, do you even know what is happening to Uyghurs in your country? No, your country bans any form of news that talks about what your country is doing to Uyghurs. Russia and China are very well known countries for banning any form of news that is negative about their own country. In the "western" world you can be critical against your own country in the news, just not allowed to spread misinformation.
> 
> > Secondly, I know that Ukraine president is tolerant towards new Nazi organization “Azov Battalion”, which admired Adolf Hitler and killed lots of innocent people in the eastern Ukraine.
> 
> You do realize that Zelensky is Jewish right?? Every country has far right-wing organizations like Nazi believers, the moment you stop them they just start over again. Would be surprised if you could give me an example of a country that has completely stopped far right-wing organizations like this.
> 
> > Thirdly, US and NATO invaded Yugoslavia in 1999, invaded Afghanistan in 2001, invaded Iraq in 2003, invaded Libya in 2011, causing war, bleeding, poverty and death. Does these mean justice and freedom?
> 
> Do you even know what was going on in Yugoslavia at the time? I recommend reading about it. Also as for Afghanistan, Russia did what it's doing in Ukraine right now with the start of Operation Storm-333. This caused lots of unrest between civilians which eventually lead to war and the start of many organizations which were trying to create peace in the country. Those organizations were later funded by the USA/UN trying to make them succeed. This failed horrible due to corruption in said organizations, which lead to the USA/UN invading Afghanistan in 2001 trying to restore peace. Educate yourself.
> 
> Now stop talking about this.

  Hahaha, actually, many aunt is exactly uyghurs. Her life is so rich and happy in China. What you saw before may be fake news from BBC or CNN. The excuses for American and NATO's intrusion are untenable and funny. 
  Now stop talking about this.

**Comment by JiangYanting** [comment]
> > Firstly,I know Twitter, Facebook and other social media are banning news, essays and accounts which support Russia. And what you see from media is likely to be biased. Does "western freedom" mean only allowing one to criticize the other, while the other cannot speak?
> 
> Facebook and Twitter are banning accounts that say there is nothing bad going on in Ukraine. Which is the complete opposite of what is going on. Also you're Chinese, do you even know what is happening to Uyghurs in your country? No, your country bans any form of news that talks about what your country is doing to Uyghurs. Russia and China are very well known countries for banning any form of news that is negative about their own country. In the "western" world you can be critical against your own country in the news, just not allowed to spread misinformation.
> 
> > Secondly, I know that Ukraine president is tolerant towards new Nazi organization “Azov Battalion”, which admired Adolf Hitler and killed lots of innocent people in the eastern Ukraine.
> 
> You do realize that Zelensky is Jewish right?? Every country has far right-wing organizations like Nazi believers, the moment you stop them they just start over again. Would be surprised if you could give me an example of a country that has completely stopped far right-wing organizations like this.
> 
> > Thirdly, US and NATO invaded Yugoslavia in 1999, invaded Afghanistan in 2001, invaded Iraq in 2003, invaded Libya in 2011, causing war, bleeding, poverty and death. Does these mean justice and freedom?
> 
> Do you even know what was going on in Yugoslavia at the time? I recommend reading about it. Also as for Afghanistan, Russia did what it's doing in Ukraine right now with the start of Operation Storm-333. This caused lots of unrest between civilians which eventually lead to war and the start of many organizations which were trying to create peace in the country. Those organizations were later funded by the USA/UN trying to make them succeed. This failed horrible due to corruption in said organizations, which lead to the USA/UN invading Afghanistan in 2001 trying to restore peace. Educate yourself.
> 
> Now stop talking about this.

Hahaha, actually, my aunt and uncle are exactly uyghurs. Their life are so rich and happy in China. What you saw before may be fake news from BBC or CNN. The excuses for American and NATO's intrusion are untenable and funny.
Now stop talking about this.

**Comment by Ycirn** [comment]
Can someone get rid of this clown?

**Comment by JiangYanting** [comment]
> > Firstly,I know Twitter, Facebook and other social media are banning news, essays and accounts which support Russia. And what you see from media is likely to be biased. Does "western freedom" mean only allowing one to criticize the other, while the other cannot speak?
> 
> Facebook and Twitter are banning accounts that say there is nothing bad going on in Ukraine. Which is the complete opposite of what is going on. Also you're Chinese, do you even know what is happening to Uyghurs in your country? No, your country bans any form of news that talks about what your country is doing to Uyghurs. Russia and China are very well known countries for banning any form of news that is negative about their own country. In the "western" world you can be critical against your own country in the news, just not allowed to spread misinformation.
> 
> > Secondly, I know that Ukraine president is tolerant towards new Nazi organization “Azov Battalion”, which admired Adolf Hitler and killed lots of innocent people in the eastern Ukraine.
> 
> You do realize that Zelensky is Jewish right?? Every country has far right-wing organizations like Nazi believers, the moment you stop them they just start over again. Would be surprised if you could give me an example of a country that has completely stopped far right-wing organizations like this.
> 
> > Thirdly, US and NATO invaded Yugoslavia in 1999, invaded Afghanistan in 2001, invaded Iraq in 2003, invaded Libya in 2011, causing war, bleeding, poverty and death. Does these mean justice and freedom?
> 
> Do you even know what was going on in Yugoslavia at the time? I recommend reading about it. Also as for Afghanistan, Russia did what it's doing in Ukraine right now with the start of Operation Storm-333. This caused lots of unrest between civilians which eventually lead to war and the start of many organizations which were trying to create peace in the country. Those organizations were later funded by the USA/UN trying to make them succeed. This failed horrible due to corruption in said organizations, which lead to the USA/UN invading Afghanistan in 2001 trying to restore peace. Educate yourself.
> 
> Now stop talking about this.

Hahaha, actually, my aunt and uncle are exactly uyghurs. Their life are so rich and happy in China. What you saw before are totally fake news (may be from BBC or CNN?). The excuses for American and NATO's intrusion are untenable and funny.
  Now stop talking about this.

**Comment by RyanBin0126** [comment]
> Can someone get rid of this clown?

It looks like you're the brainwashed clown who was blinded in biased or false report.

**Comment by Ycirn** [comment]
Remind me why this is banned in China

![image](https://user-images.githubusercontent.com/52493150/156893122-fb2baeaf-7b37-4ad2-a87c-831791cc7768.png)

**Comment by Bismuth-333** [comment]
> Hahaha, actually, my aunt and uncle are exactly uyghurs. Their life are so rich and happy in China. What you saw before are totally fake news (may be from BBC or CNN?). The excuses for American and NATO's intrusion are untenable and funny. Now stop talking about this.

Someone's been spoon-fed propaganda and misinformation by their government.

> It looks like you're the brainwashed clown who was blinded by biased and false reports.

Which false reports exactly?

**Comment by Bismuth-333** [comment]
> [https://pics1.baidu.com/feed/d53f8794a4c27d1e8cbe5d0a33df5467dcc43873.png?token=1643c839ba48604ee165dd189b6fce2d](https://github.com/ajax-lives/NoRussian/issues/url)

Also what even is this? America may not have had the best track record, but Russia sure isn't invading Ukraine to protect the Russian people. Putin is doing everything because he wants to, completely ignoring what the Russian people think. Ukraine surrendered their nuclear weapons to Russia with the promise that Russia would not invade them, but look how that turned out.

**Comment by RyanBin0126** [comment]
> > Hahaha, actually, my aunt and uncle are exactly uyghurs. Their life are so rich and happy in China. What you saw before are totally fake news (may be from BBC or CNN?). The excuses for American and NATO's intrusion are untenable and funny. Now stop talking about this.
> 
> Someone's been spoon-fed propaganda and misinformation by their government.
> 
> > It looks like you're the brainwashed clown who was blinded by biased and false reports.
> 
> Which false reports exactly?

The Wrong Story was the BBC's report on China's oppression of Uighurs in Xinjiang. At least 44 ethnic groups have long lived in Xinjiang. I grew up in Xinjiang, and I have many friends from ethnic minorities, including Uighurs. I'm still in close contact with them, and I've never seen or heard my friends talk about what the BBC calls oppression. They have never been oppressed.

**Comment by RyanBin0126** [comment]
> > > Hahaha, actually, my aunt and uncle are exactly uyghurs. Their life are so rich and happy in China. What you saw before are totally fake news (may be from BBC or CNN?). The excuses for American and NATO's intrusion are untenable and funny. Now stop talking about this.
> > 
> > 
> > Someone's been spoon-fed propaganda and misinformation by their government.
> > > It looks like you're the brainwashed clown who was blinded by biased and false reports.
> > 
> > 
> > Which false reports exactly?
> 
> The Wrong Story was the BBC's report on China's oppression of Uighurs in Xinjiang. At least 44 ethnic groups have long lived in Xinjiang. I grew up in Xinjiang, and I have many friends from ethnic minorities, including Uighurs. I'm still in close contact with them, and I've never seen or heard my friends talk about what the BBC calls oppression. They have never been oppressed.

Why do many people prefer to believe disembodied reports rather than the people who actually live there?

**Comment by RyanBin0126** [comment]
> Remind me why this is banned in China
> 
> ![image](https://user-images.githubusercontent.com/52493150/156893122-fb2baeaf-7b37-4ad2-a87c-831791cc7768.png)

https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=68018901_2_oem_dg&wd=%E7%BB%B4%E5%B0%BC%E7%86%8A&oq=%25E7%2599%25BE%25E5%25BA%25A6&rsv_pq=e1dbc03500b35af6&rsv_t=47d2rM0TL5JHTxIiFmjwbT7CtlJX%2BQBqHarQkgAJT00AsJGaPs1qeWA2Edwrhrg4UB5XpCkhjDs&rqlang=cn&rsv_enter=1&rsv_dl=tb&rsv_sug3=10&rsv_sug1=2&rsv_sug7=100&bs=%E7%99%BE%E5%BA%A6

In fact, there is no ban on Winnie the Pooh on China's largest search engine or any social media. For example, Baidu, Tik Tok China, Weibo, and so on. Just use it for yourself and you'll see.

**Comment by Bismuth-333** [comment]
![Xi-Jinping-Winnie-the-Pooh](https://user-images.githubusercontent.com/61724664/156905143-36be329e-d9dc-44e6-a856-c3562d9acc4b.jpg)
What about this?

![maxresdefault](https://user-images.githubusercontent.com/61724664/156905169-d49901f3-0413-4152-b6af-4867f018825c.jpg)
Or this?

**Comment by RyanBin0126** [comment]
> ![Xi-Jinping-Winnie-the-Pooh](https://user-images.githubusercontent.com/61724664/156905143-36be329e-d9dc-44e6-a856-c3562d9acc4b.jpg) What about this?
> 
> ![maxresdefault](https://user-images.githubusercontent.com/61724664/156905169-d49901f3-0413-4152-b6af-4867f018825c.jpg) Or this?

Why are you so complacent about insulting your country's leaders？

**Comment by Bismuth-333** [comment]
https://en.wikipedia.org/wiki/Uyghur_genocide
You should read this sometime, or maybe one of its 508 listed article citations and 6 book sources

**Comment by Bismuth-333** [comment]
> > ![Xi-Jinping-Winnie-the-Pooh](https://user-images.githubusercontent.com/61724664/156905143-36be329e-d9dc-44e6-a856-c3562d9acc4b.jpg) What about this?
> > ![maxresdefault](https://user-images.githubusercontent.com/61724664/156905169-d49901f3-0413-4152-b6af-4867f018825c.jpg) Or this?
> 
> Why are you so complacent about insulting your country's leaders？

MY country's? Buddy I'm American

**Comment by RyanBin0126** [comment]
> > > ![Xi-Jinping-Winnie-the-Pooh](https://user-images.githubusercontent.com/61724664/156905143-36be329e-d9dc-44e6-a856-c3562d9acc4b.jpg) What about this?
> > > ![maxresdefault](https://user-images.githubusercontent.com/61724664/156905169-d49901f3-0413-4152-b6af-4867f018825c.jpg) Or this?
> > 
> > 
> > Why are you so complacent about insulting your country's leaders？
> 
> MY country's? Buddy I'm American

I'm not saying this is your country's leader. You mean these pictures could be banned in China, right? I mean, would you want your friends, your parents, anyone you like or respect to be made fun of in this way?

**Comment by Bismuth-333** [comment]
There's a thing called "criticism", something that people give when they are upset with a person, company, organization, or government. It happens a lot, to everyone. The only reason he's being made fun of this way is because the West finds it funny, and it kind of is. I mean, our own leaders get made fun of A LOT more, especially we have a thing called Freedom of Speech.

**Comment by RyanBin0126** [comment]
> 

https://www.bilibili.com/video/BV1J4411y71d/?spm_id_from=333.788.recommend_more_video.-1
Freedom of Speech？On Youtube, many Youtuber who speaks for China will be restricted and inexplicably removed from fans who have already subscribed.

**Comment by RyanBin0126** [comment]
> There's a thing called "criticism", something that people give when they are upset with a person, company, organization, or government. It happens a lot, to everyone. The only reason he's being made fun of this way is because the West finds it funny, and it kind of is. I mean, our own leaders get made fun of A LOT more, especially since we have a thing called Freedom of Speech.

https://www.bilibili.com/video/BV1J4411y71d/?spm_id_from=333.788.recommend_more_video.-1
Freedom of Speech？On Youtube, many Youtuber who speaks for China will be restricted and inexplicably removed from fans who have already subscribed.

**Comment by Bismuth-333** [comment]
That video clearly shows how the CCP has influenced companies into adopting their harsh censorship across EVERYTHING. Over here, any and all censorship is done based on each individual company, **not the government**. The reason YouTube is censoring Chinese material is because they have the right to, **not because the government told them**. Tell me, how much anti-CCP content do you see created and posted by Chinese people, that stays up. Because over in America, there's **PLENTY** of anti-government material as the people are entitled to their right of criticizing the government in any way they want (granted they are not threats)

**Comment by RyanBin0126** [comment]
> That video clearly shows how the CCP has influenced companies into adopting their harsh censorship across EVERYTHING. Over here, any and all censorship is done based on each individual company, **not the government**. The reason YouTube is censoring Chinese material is because they have the right to, **not because the government told them**. Tell me, how much anti-CCP content do you see created and posted by Chinese people, that stays up. Because over in America, there's **PLENTY** of anti-government material as the people are entitled to their right of criticizing the government in any way they want (granted they are not threats)

https://www.bilibili.com/video/BV1Mb411r7oX?spm_id_from=333.337.search-card.all.click

**Comment by JiangYanting** [comment]
> That video clearly shows how the CCP has influenced companies into adopting their harsh censorship across EVERYTHING. Over here, any and all censorship is done based on each individual company, **not the government**. The reason YouTube is censoring Chinese material is because they have the right to, **not because the government told them**. Tell me, how much anti-CCP content do you see created and posted by Chinese people, that stays up. Because over in America, there's **PLENTY** of anti-government material as the people are entitled to their right of criticizing the government in any way they want (granted they are not threats)

  As a saying goes in China, "You are not fish, and don't know fish's happiness". You insists that CPC and Chinese government are fooling and oppressing their people. However actually, the income, the predicted lifespan and happiness index of Chinese people are increasing quickly in recent years. And China's GDP will exceed America soon.
  All the Chinese people have got rid of poverty in 2019. And Faced with cruel Covid-19 virus, President Xi, CPC and Chinese government have led their people to control the infection successfully.  However, how about America? 
  Many my classmates and colleagues are working in Stanford university，university of California, Berkeley and university of Washington. And they said to me that the anti-virus battle of Trump and Biden's government is absolutely failed. And the total number of Covid-19 death cases in America is over 980000, while by contrast, this number in China is only less than 8000. Is US government really responsible to their people?

**Comment by RyanBin0126** [comment]
> https://en.wikipedia.org/wiki/Uyghur_genocide You should read this sometime, or maybe one of its 508 listed article citations and 6 book sources

Too many biased or out of context, even false reports in this wiki. It would take too long to refute all of them, but if you really want to believe what is written by people who are obviously politically hostile to China, rather than the people who actually live here, I can't help it. If you have a chance to visit Xinjiang, China, maybe you will change your mind.

**Comment by ajax-lives** [comment]
Closing for very obvious reasons, lol.

For future notice - everyonr except that jackass - your responses are appreciated - however, it is much more productive and easy to ignore idiots 👍 😃
