### ISSUE TITLE
Website down (DNS ?)

### ISSUE THREAD

**Issue by deputinizer** [ajax-lives/NoRussian#70]
In Chrome:
```
This site can’t be reached
Check if there is a typo in norussian.xyz.
DNS_PROBE_FINISHED_NXDOMAIN
```

```
dig www.norussian.xyz @1.1.1.1
;; AUTHORITY SECTION:
xyz.			3598	IN	SOA	ns0.centralnic.net. hostmaster.centralnic.net.
```

Meanwhile, another project works flawlessly :smile: https://github.com/erkexzcx/stoppropaganda

**Comment by Ycirn** [comment]
The domain keeps getting taken down, probably because angry Chinese and Russian people keep reporting it. I don't see a way around it for now. Self hosting is the way for now.

**Comment by ajax-lives** [comment]
Correct.  Self hosting is now the way to use this tool.

**Comment by ajax-lives** [comment]
Or via https://ajax-lives.github.io/NoRussian/

**Comment by Ycirn** [comment]
> Or via https://ajax-lives.github.io/NoRussian/

that works

**Comment by JeniCzech92** [comment]
https://stopputin.ddns.net - I even added some additional sites.

**Comment by ajax-lives** [comment]
Please don't self advertise or post random URLs.
