### ISSUE TITLE
Wrong calls to fetchWithTimeout?

### ISSUE THREAD

**Issue by dmzi** [ajax-lives/NoRussian#71]
This seems to just call "https://ajax-lives.github.io/NoRussian/[object%20Object]" over again

Line 413:
fetchWithTimeout(target, 2000)
should be this:
fetchWithTimeout(url, 2000)

Am I missing something?

**Comment by Ycirn** [comment]
@naslundx I believe this orginates from your PR

**Comment by Ycirn** [comment]
Solved by reverting

**Comment by dmzi** [comment]
My what? Pull Request? I didn't do any.
.. and I see, it is corrected now

**Comment by Ycirn** [comment]
> My what? Pull Request? I didn't do any. .. and I see, it is corrected now

I mentioned the guy who made the pull request that broke the code
