### ISSUE TITLE
This tool does nothing and its literally useless

### ISSUE THREAD

**Issue by cpueasy** [ajax-lives/NoRussian#73]
YOU ARE A MONKEY
YOU ARE AN APE
RUSSIA DID NOTHING WRONG

**Comment by Ycirn** [comment]
troll

**Comment by cpueasy** [comment]
No, Russia did nothing wrong. This tool is useless as all Russian websites are blocked anyways. I'm literally in Russia I know better

**Comment by Ycirn** [comment]
@ajax-lives get rid of this brainwashed kacap

**Comment by cpueasy** [comment]
![image](https://user-images.githubusercontent.com/88821057/156930613-978cb37c-9211-4e93-a533-8340227daa34.png)
hey look guys I found @Ycirn

**Comment by cpueasy** [comment]
https://www.google.com/maps/d/u/0/viewer?mid=1DZtmQOsq6UBodj8zgB9WC_9BEaY&ll=47.9415218726191%2C37.54165384070755&z=14
https://www.youtube.com/watch?v=i2ILlui2HmI man look at these violent hated separatists!
![image](https://user-images.githubusercontent.com/88821057/156930692-06ad304b-50a4-4a0e-814b-bc9ad5924688.png)
https://en.wikipedia.org/wiki/Casualties_of_the_Russo-Ukrainian_War#:~:text=War%20in%20Donbas,-Main%20article%3A%20War&text=The%20overall%20number%20of%20confirmed,killed%20by%2013%20May%202021
https://www.hrw.org/news/2014/07/24/ukraine-unguided-rockets-killing-civilians
https://ru.wikinews.org/wiki/%D0%92_%D0%93%D0%BE%D1%80%D0%BB%D0%BE%D0%B2%D0%BA%D0%B5_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D0%BB%D0%B8_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB_%D0%BF%D0%BE%D0%B3%D0%B8%D0%B1%D1%88%D0%B8%D0%BC_%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%D0%BC
https://ronin-077.livejournal.com/37466.html

**Comment by cpueasy** [comment]
![image](https://user-images.githubusercontent.com/88821057/156930814-a34e99d5-d0ba-4713-b72c-98dea3362045.png)
Nice look @Ycirn @ajax-lives 
still works fine for me didn't go offline. Just not for you clowns 🤡 ✔️

**Comment by cpueasy** [comment]
@Ycirn Please support the Terrorists who killed the 15 thousand Russians over the last 8 years.
Please support brother. Hit Russian websites that are not accessible to you anyhow and keep wasting your time

**Comment by Ycirn** [comment]
> @Ycirn Please support the Terrorists who killed the 15 thousand Russians over the last 8 years. Please support brother. Hit Russian websites that are not accessible to you anyhow and keep wasting your time

Happily

**Comment by JeniCzech92** [comment]
@cpueasy : One may wonder why are you so mad about it if it's useless... Russia wants to secure a European energetic oligopoly. No matter the blood spilt. This is unacceptable.

**Comment by cpueasy** [comment]
@JeniCzech92 I hate fake news man. Sadly Ukraine is just a middleman exchange coin for the American. Russia doesn't want to secure anything but it's citizens that live in Ukraine and die due to the result of the rebels killing them
