### ISSUE TITLE
The warning modal popup is gone, why?

### ISSUE THREAD

**Issue by Ycirn** [ajax-lives/NoRussian#78]

**Comment by naslundx** [comment]
Not just that, pretty much everything I've done was swiftly removed by #77 which was merged even though it's obviously based on an older version of the site. I don't neccessarily disagree with the core stuff the PR wanted to add, but it should not have been accepted in its present form.

There seems to be no real direction here, things just get merged without review, and all my work is gone, so I'm out.

**Comment by ajax-lives** [comment]
Relax, I've reverted that PR.  Furthermore, I'll be adding you both as collaborators.

**Comment by ajax-lives** [comment]
Done.
