### ISSUE TITLE
GitHub pages deployment returns 404 error.

### ISSUE THREAD

**Issue by MadKamel** [ajax-lives/NoRussian#81]
Not sure what happened here, but it returns an error.
![Screenshot 2022-03-11 11 24 04](https://user-images.githubusercontent.com/48301203/157937293-53278d7b-442a-4346-a184-4404d75b1c35.png)
Link being used is the one in the README.md and the one listed as being actively deployed. ([Deployment](https://ajax-lives.github.io/NoRussian/))

**Comment by ajax-lives** [comment]
This is accurate.  GitHub asked us to remove it.

**Comment by ajax-lives** [comment]
You can run it locally by downloading as zip.
